sudo: required
language: java
install: true

jdk:
  - oraclejdk8
  - openjdk8

services:
 - docker

before_install:
 - gradle wrapper --gradle-version 5.0
 - gradle -v
 - gradle assemble
 - docker build -t shesh-repo/camunda-serv .

script:
 - docker run shesh-repo/cammunda-serv
git commit -m "
